package:                                                                           
  name: bf-tideprediction                                                          
  version: 0.0.1                                                                   
                                                                                   
source:                                                                            
  path: ../../bftideprediction                                                        
requirements:                                                                      
  build:                                                                           
    - gcc                                                                          
    - python                                                                       
    - numpy 1.12.0    
    - click 6.6
    - coverage 4.2
    - decorator 4.0.10
    - dill 0.2.5
    - Flask 0.11.1
    - Flask-WTF 0.12
    - gunicorn 19.6.0
    - infinity 1.4
    - intervals 0.8.0
    - itsdangerous 0.24
    - Jinja2 2.8
    - MarkupSafe 0.23
    - nose 1.3.7
    - numpy 1.11.1
    - pytides 0.0.4
    - scipy 0.18.0
    - six 1.10.0
    - SQLAlchemy 1.0.14
    - SQLAlchemy-Utils 0.32.9
    - validators 0.11.0
    - Werkzeug 0.11.10
    - WTForms 2.1
    - WTForms-Alchemy 0.16.1
    - WTForms-Components 0.10.0
    - pip:
      - flask-wtf-alchemy-utils==0.1.0
                                                                                   
  run:                                                                             
    - Flask                                                                        
    - python                                                                       
                                                                                   
build:                                                                             
  string: py{{py}}_0                                                               
  binary_relocation: False                                                         
                                                                                   
about:                                                                             
  home: https://github.com/venicegeo/bf-tidepredcition                             
  summary: "Some desc here"                                                                   
  license: Apache 2.0